#include "../src/render/opengles2/SDL_gles2funcs.h"
SDL_PROC(void, glUniform1f, (GLint, GLfloat))
SDL_PROC(void, glBindVertexArray, (GLuint))
SDL_PROC(void, glUniform2fv, (GLint, GLsizei, const GLfloat *))
SDL_PROC(void, glGenVertexArrays, (GLsizei, GLuint *))
SDL_PROC(void, glGetShaderSource, (GLuint, GLsizei,	GLsizei *, GLchar *))
SDL_PROC(void, glDetachShader, (GLuint, GLuint))
SDL_PROC(void, glVertexAttrib1f, (GLuint, GLfloat))
SDL_PROC(void, glVertexAttrib2f, (GLuint, GLfloat, GLfloat))
SDL_PROC(void, glVertexAttrib3f, (GLuint, GLfloat, GLfloat, GLfloat))
SDL_PROC(void, glVertexAttrib4f, (GLuint, GLfloat, GLfloat, GLfloat, GLfloat))
SDL_PROC(void, glUniform2f, (GLint, GLfloat, GLfloat))
SDL_PROC(void, glUniform3f, (GLint, GLfloat, GLfloat, GLfloat))
SDL_PROC(void, glUniform1iv, (GLint, GLsizei, const GLint *))
SDL_PROC(void, glUniform1fv, (GLint, GLsizei, const GLfloat *))
SDL_PROC(void, glUniform3fv, (GLint, GLsizei, const GLfloat *))
SDL_PROC(void, glUniform4fv, (GLint, GLsizei, const GLfloat *))